### ISSUE TITLE
More concrete types for proxies.ts

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/evm-tableland#108]
Use more concrete types in `proxies.ts`. Right now it's `[key: string]` which means we have to add a new more concrete type in `js-tableland`

**Comment by sanderpick** [comment]
We should also add chain ID to proxies.

**Comment by sanderpick** [comment]
And... tableland "testnet" / "staging"

**Comment by carsonfarmer** [comment]
Plus one to this issue, _plus_ adding the chain IDs means we aren't hand-coding this information in the sdk. It also means we'll get typed network names through our sdk and cli libs.
