### ISSUE TITLE
[REVM-25] Support an additional layer for mapping db files with table aliases to actual table NFTs

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/evm-tableland#132]
### Is your feature request related to a problem? Please describe.
There is DX friction related to a "complex" table's name `prefix_chainId_tableId` as well as managing all tables related to a single application. 

For example, there one day could be a table name like this: `mytable_1_115792089237316195423570985008687907853269984665640564039457584007913129639935`. It'd be nice if I could abstract that complicated table name away and _alias_ this table with a custom one, similar to an ENS-like feature.

Additionally, with a typical database, I have a `.db` / `.sqlite` file that contains a bunch of tables for my app. This would also be a great feature to have -- a _namespace_ that acts as a grouping for a series of table _aliases_. Both of these ideas can also lead to better table upgradability patterns, enable emulation for `DROP` and `ALTER` actions, and would work well with (a separate) idea for _forking_ a table's state. E.g., to alter a table means to fork it & create a new table -- the validator copies the _source_ table's data at some block, and the SC updates the alias to point to the new 
_target_ table that was minted.

**This feature request is focused on the _namespace_ and _alias_ aspects, only.**

### Describe the solution you'd like
1. Create an ENS-like table _alias_ feature for single table names.
2. Create a `.db`-like feature for grouping table aliases together.

For example, let's say I have a project with tables `main_1_1` and `attributes_1_2` for my NFT collection called `rigs`. With the two points outlined above, I could register some namespace `rigs`, and I could alias the tables with something like `main` and `attributes` that are contained by `rigs`. Thus, the final output is rather similar to a typical SQLite setup where `rigs.db` holds the aliases `main` and `attributes` (which point to `main_1_1` and `attributes_1_2`).

From an implementation perspective, additional work is needed to determine how this could be achieved, such as a new ERC721 vs. 1155 vs. { some other } contract in which the registry reads from. Regardless, a good example to reference would be the [ENSRegistry contract](https://github.com/ensdomains/ens/blob/master/contracts/ENSRegistry.sol).

### Describe alternatives you've considered
_Not_ using namespaces / aliases, which is the current state. The DX can be better.

### Additional context
Idea originally described in a TPD [here](https://www.notion.so/textile/Proposal-for-TABLE-aliases-to-enable-table-upgradability-data-migration-patterns-9bd55564acb446cf8fd3de93ec083277).

<sub>[REVM-25](https://linear.app/tableland/issue/REVM-25/support-an-additional-layer-for-mapping-db-files-with-table-aliases-to)</sub>

**Comment by joewagner** [comment]
RE: Growth guild call today
Here's a ref of a simple use of JS ENS lookup https://github.com/tablelandnetwork/example-apps/blob/main/gila/frontend/store/index.ts#L190

**Comment by sanderpick** [comment]
I think this is covered in the ENS experiment. Sound right @dan ?
