### ISSUE TITLE
[REVM-26] Create a single runSQL endpoint that can handle multiple writes and creates

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/evm-tableland#134]
### Discussed in https://github.com/orgs/tablelandnetwork/discussions/231

<div type='discussions-op-text'>

<sup>Originally posted by **sanderpick** August 19, 2022</sup>
Tension: https://github.com/orgs/tablelandnetwork/discussions/230

We want to let a single txn touch multiple tables. Here's a proposal for altering `TablelandTables` to enable this.

---

Create an overloaded version of `runSQL` that takes an array of structs containing a table ID and an array of SQL statements. Pseudo-ish code:

```
struct Runnable {
    uint256 tableId;
    string[] statements;
}
```

```
function runSQL(
    address caller,
    Runnable[] memory runs,
) external payable;
```

- For many statements against the same table, the table ID doesn’t need to be repeated (but you could still have multiple structs against the same table, if this ordering was important to you)
- ACL check could be performed once per struct instance (vs. grouping in the contract which has some computational cost)

I also like the idea of including table creation in a single endpoint like this. We could say that if the table ID is not defined (has its default value of 0), then interpret it as “create table”.

With a SQL parser available to clients, SDKs could map a plain list of SQL statements to an array of `Runnable` (or similarly named object). That is to say, using the API would be abstracted from users in some UX friendly way. </div>

<sub>[REVM-26](https://linear.app/tableland/issue/REVM-26/create-a-single-runsql-endpoint-that-can-handle-multiple-writes-and)</sub>

**Comment by carsonfarmer** [comment]
I'd like to bump this one from the SDKs perspective as well. This could enabled a lot of use cases like building up a set of tables and seeding them with data to bootstrap an apps setup etc.

**Comment by joewagner** [comment]
Makes sense, I'll start on this asap

**Comment by joewagner** [comment]
@carsonfarmer This is in the evm-backlog project, does it make sense to create a different project for this work and sync that with a project in notion?

**Comment by carsonfarmer** [comment]
Yeh that's a good question. I'm not sure. This _might_ fall under some of the API refactor work to a degree, though we were trying to separate on the on-chain stuff from the validator APIs in that work. Perhaps leave it in the backlog for now?

**Comment by joewagner** [comment]
> Yeh that's a good question. I'm not sure. This _might_ fall under some of the API refactor work to a degree, though we were trying to separate on the on-chain stuff from the validator APIs in that work. Perhaps leave it in the backlog for now?

Sounds good to me.
