### ISSUE TITLE
We should switch to more standard naming conventions when working with chain names

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/evm-tableland#237]
**The issue**
Currently, across our SDKs and libraries, we reference the following chain specifiers:

- ethereum
- optimism
- arbitrum
- polygon
- ethereum-goerli
- optimism-goerli
- arbitrum-goerli
- polygon-mumbai
- optimism-goerli-staging
- localhost

However, these specifiers are specific to Tableland. For instance, `ethersjs` (and https://chainlist.org) use the [following equivalent set](https://github.com/ethers-io/ethers.js/blob/master/packages/networks/src.ts/index.ts#L135):

- mainnet (alias homestead)*
- optimism
- arbitrum
- matic*
- goerli*
- optimism-goerli
- arbitrum-goerli
- maticmum*
- optimism-goerli (with our own `staging` suffix?)
- localhost

For localhost, I think hardhat has a convention here, and I think perhaps @joewagner also had an opinion on this one?

**Describe the solution you'd like**
It would be useful to adopt the above naming conventions in this repo, and in our SDK and CLI tooling, so that a) it is easier for devs to cross over when dealing with chains and networks, and b) so that our code is more directly compatible with ethers and other projects.

**Describe alternatives you've considered**
At the moment, supporting our own naming conventions require a mapping in the SDK or CLI from Tableland names to external names. This isn't the end of the world, but it does mean that we end up duplicating names across places, rather than having a single source of truth that we can just use "as is".

**Comment by carsonfarmer** [comment]
cc @sanderpick @brunocalza @dtbuchholz @joewagner

**Comment by joewagner** [comment]
Looked at the implications of this today, and I like your suggestions.  The hardhat localhost convention works well with the newest version of local-tableland. 
There is an issue with having multiple registries on the same chain, but adding `-staging`, `-dev`, etc... solves that problem nicely imo.

**Comment by carsonfarmer** [comment]
Hey @joewagner , do you think we could get this plus the update from testnet to testnets in for the network separation work this milestone? Do you have some time for this update? Perhaps we can publish it under a "next" or "dev" tag?

**Comment by joewagner** [comment]
@carsonfarmer RE: naming conventions.  
Last week I was working through building tests for hardhat projects, and @asutula has been building a local-tableland hardhat extension. There's been a need to distinguish between `localhost` and `local-tableland`.  This is because if hardhat is run with the network is equal to `localhost` Hardhat will be expecting a standalone hardhat node to already be running.

@asutula might have more to say here, but I believe that if we want to enable a hardhat plugin that sets up and runs local-tableland internally we have to support a name other than `localhost`

Maybe we can support both, and document the differences?

**Comment by asutula** [comment]
In my hardhat plugin, I'm leveraging a new/unique network name `local-tableland`. It is functionally the same as `localhost` but used by the plugin to distinguish between the user's intent to run hardhat tasks in the traditional/unmodified `localhost` mode vs the plugin's magic of running `local-tableland` mode instead. So, yes I think it would be nice to support `local-tableland` as a network in the SDK.

**Comment by carsonfarmer** [comment]
In that case, will the hardhat network that is running still be running at the same default port etc? As in, is there a world in which both a hardhat plugin (raw) and a hardhat plugin (tableland) will be running at the same time on different ports?

**Comment by joewagner** [comment]
> In that case, will the hardhat network that is running still be running at the same default port etc? As in, is there a world in which both a hardhat plugin (raw) and a hardhat plugin (tableland) will be running at the same time on different ports?

I can't think of a reason to do that.

**Comment by carsonfarmer** [comment]
Cool, then I think from the SDK's perspective, both scenarios are the same, and they are just `"localhost"`. In both cases, it'll target 8080 for the API, and whatever the default hardhat JSON RPC API port is.

**Comment by asutula** [comment]
Yea, the settings for `localhost` and `local-tableland` should be exactly the same. The only distinction is external to the sdk, and only to determine correct intent/behavior around running local tableland or plain hardhat.

**Comment by carsonfarmer** [comment]
Peeerfect
