### ISSUE TITLE
[REVM-17] We should avoid statement size checks in the contract in favor of checking in clients

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/evm-tableland#260]
**Describe the bug**
Right now, we check for statement size in our smart contract to ensure all statements are under the our network 35kb limit. This check actually costs the caller gas, and for very large statements, we will actually run out of gas before we actually perform the check itself. This makes it essentially wasteful and not particularly useful. And when we make a call where the checks _will_ pass, then it is again wasteful because we essentially already know it will pass.

**To Reproduce**
I'm going to tag @joewagner here for more context from his tests.

**Expected behavior**
We should just perform these checks in a standard way on clients, and in the validators, but _not_ in the contract where it costs gas.

<sub>[REVM-17](https://linear.app/tableland/issue/REVM-17/we-should-avoid-statement-size-checks-in-the-contract-in-favor-of)</sub>

**Comment by carsonfarmer** [comment]
The current limits are based on this research: https://www.notion.so/textile/Query-Limit-Investigation-d6c7ae2afe354d6b9b3e1867a9e94caa This is all important and useful, but we can optimize (where) we actually do the checks.

**Comment by brunocalza** [comment]
Just adding some thoughts and clarifications

I agree that having a check in the client is pretty good, but not sure if we should remove the check from the contract. You can always call the contract directly, and allowing a big txns to be made in the contract opens the door to unexpected errors in the contract hard to debug, and different experiences across chains. 

Regarding the comment
> we will actually run out of gas before we actually perform the check itself

I don't think that will actually happen. The value for the limit was thought considering the usage of gas. All networks were tested with a 35kb query.

**Comment by jsign** [comment]
@carsonfarmer, I see this is assigned to the _New APIs_ project but I don't think it's related. Shouldn't this be part of the _SDK Refactor_ if we plan to do the length check at the SDK level?

**Comment by jsign** [comment]
As to comment on the discussion, I agree with @brunocalza  that keeping the check in the contract is good. Checking as many things as possible in the client is good to avoid gas usage.

**Comment by jsign** [comment]
> @carsonfarmer, I see this is assigned to the _New APIs_ project but I don't think it's related. Shouldn't this be part of the _SDK Refactor_ if we plan to do the length check at the SDK level?

@carsonfarmer, bumping this question.

**Comment by joewagner** [comment]
I was going to chime in here and it fell through the cracks.

I was trying to get better test coverage for this repo and I noticed that because of the block limit of 30 million gas for ethereum the conditional was not ever being called.  For our contract on Ethereum the block gas limit is reached when a query gets to be around 14.5kb.  (It might be worth explaining this in the docs)
After re-reading Bruno's writeup it sounds like the size check is needed for other chains, and it seems ok to have callers pay a little more gas and keep the check.

I'm ok closing this since the check is needed for chains other than Ethereum

**Comment by dtbuchholz** [comment]
@joewagner adding...basically, the callout should only be for Ethereum and Ethereum alone?

**Comment by joewagner** [comment]
@dtbuchholz Yeah this is specific to Ethereum

**Comment by jsign** [comment]
I didn't get feedback reg my questions before, so I removed this issue from the _New APIs_ project.

**Comment by sanderpick** [comment]
@carson is this one closable?

**Comment by carsonfarmer** [comment]
Possibly? It has been handled on the client. So we should just close this and reopen if it comes up again.
