### ISSUE TITLE
update getPolicy method to provide the tableId(s) being modified

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/evm-tableland#264]
This is a bit tricky. But right now the Controller method looks like,

```
interface ITablelandController {
    /**
     * @dev Object defining how a table can be accessed.
     */
    struct Policy {
        bool allowInsert;
        bool allowUpdate;
        bool allowDelete;
        string whereClause;
        string withCheck;
        string[] updatableColumns;
    }

    /**
     * @dev Returns a {Policy} struct defining how a table can be accessed by `caller`.
     */
    function getPolicy(address caller) external payable returns (Policy memory);
}
```

This presents a problem for smart contracts that provide the controller for multiple tables. They all have to have the same policy, or you need different contracts for every policy. This is a new problem for contracts that generate tables dynamically and then want to assign ACL to those tables. 

Instead, something like this would be great,

```
interface ITablelandController {
    /**
     * @dev Object defining how a table can be accessed.
     */
    struct Policy {
        bool allowInsert;
        bool allowUpdate;
        bool allowDelete;
        string whereClause;
        string withCheck;
        string[] updatableColumns;
    }

    /**
     * @dev Returns a {Policy} struct defining how a table can be accessed by `caller`.
     */
    function getPolicy(address caller, uint256 tokenId) external payable returns (Policy memory);
}
```

gut check that an insert/update can only modify one table at a time?

If that's true, them the above is a good fix. if it's not true, we'll need to think of arrays or something. 

side note, this also ignores prefixes in the getPolicy... just future proofing it to not worry about those.

**Comment by joewagner** [comment]
> gut check that an insert/update can only modify one table at a time?

My understanding is that when the validator parses mutating queries it checks that they all affect the same table [here](https://github.com/tablelandnetwork/go-tableland/blob/main/pkg/parsing/impl/validator.go#L117-L147).  Someone with more familiarity can double check me thought.

**Comment by joewagner** [comment]
I have a couple of initial reactions to this idea:
 - There might be an increase in gas (but maybe irrelevant if we use function overloading?).
 - Do we have an example or a specific use-case?  Would it be better to put the decision logic in the contract creating the table vs. inside the policy contract?

**Comment by andrewxhill** [comment]
> There might be an increase in gas (but maybe irrelevant if we use function overloading?).

There should be negligible gas increase. I checked the controller method on the registry, it already knows the tableId when it checks, so it's just about passing a couple bytes to the controller getPolicy endpoint. 

> Do we have an example or a specific use-case? Would it be better to put the decision logic in the contract creating the table vs. inside the policy contract?

Yeah, we are saying the same thing. The problem is, you cannot without this fix. 

Steps to recreate. (this is just a toy, not worth evaluating this example)

1. You write a smart contract that is an ERC721. 
2. Every time a user mints a new NFT, a new table is generated that is attached to the NFT. 1 to 1, NFT to table.
3. The contract owns the table but calls the set controller method, telling the Tableland Registry to call its own getPolicy method. 
4. A user mints a new NFT, a new table is created to power it.
5. The user loads some front end Dapp using the Tableland SDK that reads the NFT and sees the table connected.
6. The user does something in the dapp and uses the SDK to hit, tableland.runSQL("update target_table change some stuff").

This is where the problem hits. 

The runSQL command goes directly to the Tableland registry.

update statement => tableland registry => registry calls getPolicy() => goes back to NFT smart contract

The NFT smart contract, the way it is currently implemented, has no idea which table that getPolicy is asking about (recall, the NFT smart contract has 100s of tables, 1 to 1 for every NFT). So it can't make any decision logic. 

### Solutions

1. We scrap using Controllers, and instead make all contracts implement their own ITablelandTables interface and parse any runSQL etc _before_ passing it to tableland. I've played with this too, it's a good solution for some apps and can be done irregardless of other fixes. So yes, but not perfect / great dx. It requires the app to use the CLI and SDK in a specific way by pointing to their own contracts and it has some real setup costs. Again, not terrible, but not perfect.
2. We register a different getPolicy endpoint for every NFT minted. It's not possible, the Controller method requires that exact getPolicy endpoint method name/abi. Maybe the NFT contract could factory new contracts for every NFT... but that's nuts and costly.
3. We modify getPolicy to pass the tableId back to the Controller. This feels pretty sane to me, it allows the decision logic to go to the contract creating the table (as you suggest) as it's not possible today.

**Comment by sanderpick** [comment]
this looks to be a duplicate of https://github.com/tablelandnetwork/evm-tableland/issues/156

**Comment by andrewxhill** [comment]
hey hey, look at that. closing.
