### ISSUE TITLE
Having trouble calling runSQL on table that implements Policy Contract based access control after burning

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/evm-tableland#30]
This conditional might be disabling the possibility of using Policy Contract based access control https://github.com/tablelandnetwork/eth-tableland/blob/c44c6bd14c29006e8ac397632a352452f0499846/contracts/TablelandTables.sol#L71

The check reverts with an "Unauthorized" error if the call to `_exists()` returns false.  As far as I can tell using `_burn(tableId)` results in the tableId no longer "existing".  Which in turn results in the calls to run sql always failing.  
I'm able to burn the table and still access it according to the policy contract rules if I transfer to a burn address like `0x000000000000000000000000000000000000dead`.

There also might be an error in my code that I'm not seeing.  To reproduce setup and run the example apps chess game locally.

**Comment by sanderpick** [comment]
drilling into what `burn` does and how `_exists` is evaluated. ERC721a flips a flag indicating if a token has been burned: 

```
// The bit mask of the `burned` bit in packed ownership.
uint256 private constant BITMASK_BURNED = 1 << 224;
```

that is used in `_exists`. i can see why they did it like this: burn is the total death of the token : )

suggestion: stop inheriting from the burnable extension and define a new function:

```
/**
 * @dev Locks table ownership and access control.
 *
 * tableId - the id of the target table
*/
function lock(uint256 tableId) external;
```

for the error splitting... I thought about doing that but reverted to the REST mentality of not leaking information about the target object. If you're not authorized, you should not even know if the token exists or not. Plus it adds to the contract size.

**Comment by sanderpick** [comment]
The `lock` method would do what you did manually... send the token to some burn address, eg, `0x000000000000000000000000000000000000lock`

**Comment by joewagner** [comment]
I like the suggestion of not inheriting from burnable since it doesn't seem to work for our use cases. The `lock` function sounds perfect.  Do we need to enable it in the contract somehow?

**Comment by sanderpick** [comment]
which test are you thinking of? the link above points to your branch afaict. 

i can do a quick PR with that lock method and we can upgrade the proxies!

**Comment by joewagner** [comment]
`lock` sounds awesome!
If you checkout that branch and run the tests you'll see the "Should be able to gate run SQL with controller contract" test fail  because the table doesn't exist. It's possible that is correct, but I was interpreting it as trying to test if the call is authorized.
