### ISSUE TITLE
[REVM-27] Approved addresses don't work for createTable, runSQL, setController, lock

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/evm-tableland#33]
The Tableland methods don't support the notion of an "approved address". I'm not sure we want to, but just flagging it. Marketplaces use this concept to handle sales, auctions, etc.

Do we think it's useful to allow some other address to do things for you? Perhaps the same concept should be used for our concept of "validator proxies", which would let people actually approve / revoke this behavior.

<sub>[REVM-27](https://linear.app/tableland/issue/REVM-27/approved-addresses-dont-work-for-createtable-runsql-setcontroller-lock)</sub>

**Comment by joewagner** [comment]
There are 2 exploratory branches here:
https://github.com/tablelandnetwork/evm-tableland/tree/joe/relay-list
https://github.com/tablelandnetwork/evm-tableland/tree/joe/relay-approval
I'm not sure either of those approaches will make sense, but adding for reference

**Comment by sanderpick** [comment]
really nice. great idea to explore some different options. we can use your exploration as input to some convos over then couple weeks of convergence and planning.
