### ISSUE TITLE
[REVM-13] Test with Aaron

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/evm-tableland#343]
<sub>From [SyncLinear.com](https://synclinear.com) | [REVM-13](https://linear.app/tableland/issue/REVM-13/test-with-aaron)</sub>

**Comment by asutula** [comment]
Hi how are you

**Comment by asutula** [comment]
Another

**Comment by sanderpick** [comment]
sander ping

**Comment by asutula** [comment]
I have sync enabled now
