### ISSUE TITLE
[EVM-15] Upgrade to ethers v6

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/evm-tableland#371]
Now that Ethers v6 has been released we should start to work towards using it here so that the SDK can upgrade to v6.
There will be some complexity in upgrading. This package has ethers as a dev dependency, and some of the other dev dependencies mark ethers as a peer dependency.  Those peer dependencies all currently have ethers v5 tagged.  Looking at the github repos for these packages makes it seem like they are all going to have versions that use v6 coming out soon.
We should be ready for all those upgrades here.

related:
[https://github.com/NomicFoundation/hardhat/issues/3639](https://github.com/NomicFoundation/hardhat/issues/3639)
[https://github.com/tablelandnetwork/tableland-js/issues/41](https://github.com/tablelandnetwork/tableland-js/issues/41)

<sub>From [SyncLinear.com](https://synclinear.com) | [EVM-15](https://linear.app/tableland/issue/EVM-15/upgrade-to-ethers-v6)</sub>

**Comment by sanderpick** [comment]
cc @joewagner

**Comment by awmuncy** [comment]
Gonna have to bump this to next cycle. Nomic is close to done, it seems, but the issue is still open.

**Comment by sanderpick** [comment]
@awmuncy can you pull this into its own project? I think that would be easier to deal with… we can then close the giant tooling table stakes project.

**Comment by awmuncy** [comment]
Yep, tickets related to the Ethers v6 upgrade have been moved into their own project. And with that, the tooling table stakes project is complete.

**Comment by joewagner** [comment]
Just looked at this again. Hardhat has setup some beta support for v6, but open zeppelin has conflicting peer deps if we try to upgrade.
Looks like OZ has a dependency bot that created a PR, but it will need someone to manually upgrade.
https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/736
