### ISSUE TITLE
[REVM-28] Add url encoding helpers for raw SQL queries in uri / gateway calls

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/evm-tableland#47]
### User Story
Tableland allows for queries to be appended to the gateway url by first appending `query?s=...` to the `baseURI` -- this allows for raw SQL queries on the url itself. Then, once the `tokenURI` is called, the actual SQL query is appended to the `baseURI` to exeucte a query for that specific `tokenId` (i.e., `https://staging.tableland.network/query?s=select...` at the `tokenId`).

To avoid messy smart contract interpolation and presumed url encoding knowledge, there should exist url encoding helpers for smart contracts. Here is an example of what this looks like in the SC itself:
<img width="235" alt="Screen Shot 2022-07-03 at 6 34 43 PM" src="https://user-images.githubusercontent.com/13358940/177064835-7f3d64d7-534a-484b-a957-2815c41bcfe4.png">

To provide a non-screenshot example, the following is what must be properly encoded with `%20`, `%3D`, etc. in the SC `tokenURI` itself, which returns something like:
`https://staging.tableland.network/query?s=select%20*%20from%20rigs_69_3%20where%20id%3D1&mode=object`.

### Reuirements
_Using the example in the screenshot._ instead, support raw SQL in the SC `baseURI` such that a url encoding Solidity helper library properly transforms everything to the proper encoding.

A simple approach could be to consider with the following parameters:
```
  "SELECT * FROM",
  _metadataTable,
  "WHERE id = ",
  tokenId
```
and allow these to be passed as an interpolated string. From what I've researched, there doesn't seem to be a "nice" way to interpolate strings like in JS (`SELECT * FROM ${name}...`) or other languages, but that would be ideal. Instead, a more realistic approach would be a library that takes a single string and url encodes it (passing `"SELECT * FROM"` converts to `"SELECT%20*%20FROM"`) and so on. A sample url encoding reference can be found [here](https://www.w3schools.com/tags/ref_urlencode.ASP).

### Describe alternatives you've considered
There could be existing Solidity libraries that support this conversion, but doesn't appear that anyone has put this together (OZ, etc.) based on some brief research.

### Additional context
Example queries encoded in uri -- sharing these to demonstrate the in-SC complexity that may arise come without helpers:
* https://staging.tableland.network/query?s=select%20json_object%28%27id%27%2Cid%2C%27image%27%2Cimage%2C%27image_alpha%27%2Cimage_alpha%2C%27thumb%27%2Cthumb%2C%27thumb_alpha%27%2Cthumb_alpha%29%20from%20rigs_69_3%20limit%201&mode=list
* https://staging.tableland.network/query?s=select%20json_object%28%27id%27%2Cid%2C%27image%27%2Cimage%2C%27image_alpha%27%2Cimage_alpha%2C%27thumb%27%2Cthumb%2C%27thumb_alpha%27%2Cthumb_alpha%29%20from%20rigs_69_3%20limit%201&mode=list

<sub>[REVM-28](https://linear.app/tableland/issue/REVM-28/add-url-encoding-helpers-for-raw-sql-queries-in-uri-gateway-calls)</sub>

**Comment by dtbuchholz** [comment]
See here for an existing utility function, which can be used as a foundation for this and further extended for URL encoding: https://github.com/tablelandnetwork/evm-tableland/blob/main/contracts/utils/URITemplate.sol

**Comment by sanderpick** [comment]
another path to consider is the one we did for Rigs:
1. use a script to set a `URITemplate`: https://github.com/tablelandnetwork/rigs/blob/main/ethereum/scripts/setURITemplate.ts
2. script calls a helper method that handles all the ugly URL encoding: https://github.com/tablelandnetwork/rigs/blob/0e21628d774149dade1db713e841c58f9cb996ea/ethereum/helpers/uris.ts#L1

**Comment by sanderpick** [comment]
hey @dan. I pulled this one in from GH. i think we can close this, but let me know your thoughts.
