### ISSUE TITLE
Can only create table from constructor

### ISSUE THREAD

**Issue by wbt** [tablelandnetwork/evm-tableland#81]
**Describe the bug**
CREATE TABLE statements called from the EVN only work when called from the constructor, not from another function. 

**To Reproduce**

1. Start with [this file](https://github.com/tablelandnetwork/example-apps/blob/798c22fc85d1ebfe8fda255c2762974d8b2aea7f/canvas-game/contracts/CanvasGame.sol)
2. On lines 16-17, change the variable visibility from private to public for ease of visibility.
  \-  string private _metadataTable;
  \-   uint256 private _metadataTableId;
  \+  string public _metadataTable;
  \+  uint256 public _metadataTableId;
4. Using Hardhat, build and deploy the contract. The example was on the Mumbai testnet, passing Tableland's location (0x4b48841d4b32C4650E4ABc117A03FE8B51f38F68) to the constructor.
5. In verifying reproducibility for this Issue, this deployment is at 0xc84652Fc6340cf50216Ab5aE97AF9e35a2A8cA20 and you can still interact with it there.
6. Call the getter functions sharing a name with those two variables. For example, canvasGame._metadataTable() on that contract returns 'canvas_80001_451' - this is the expected result.
7. Just before the CREATE TABLE comment (between lines 31 and 32), add the following three lines: 
```solidity
      _createCanvasTable();
  }
  function _createCanvasTable() private onlyOwner {
```
8. Optionally build and deploy the contract again, with the exact same script. In testing to verify reproducibility, this was at 0x214d689ADF8B16A45a87d875ae6BD73C8324C631
9. Call the getter functions sharing a name with those two variables. For example, canvasGame._metadataTable() on that contract returns 'canvas_80001_454' - this is the expected result.
10. Change the new function visibility to public and optionally repeat the process.  Sample deployment is at 0x5cb30d9e1c58B83966708c3b99650E5C3B156356 and the table name is 'canvas_80001_457'.
11. Since the new function is now public, wrap its body in an `if` block: `if(_metadataTableId == 0) {`...`}`.
12. Redeploy. Deployment at 0xa7EDeF1b0af898BB28023ebeaDbBaD5246877661 has table name canvas_80001_461.
13. Comment out the constructor function's call to the table-creation function.
14. Redeploy. Example contract for this step is at 0x55346c7689D534A37226De1E69866f0117e898cb and the table name is at this point empty as expected. 
15. Attempt to call the _createCanvasTable() function from the same account used to deploy the contract.
16. Observe that this attempt will fail, with an error like this:
> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xaf8Da163793B628410C82079bBFfDABD7B8f0B25","to":"0x55346c7689D534A37226De1E69866f0117e898cb","data":"0x0f73e33e","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0xd1a57ed6"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted\",\n    \"data\": \"0xd1a57ed6\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)
    at f.makeError (index.js:219:23)
    at f.throwError (index.js:228:20)
    at Ri (json-rpc-provider.js:76:20)
    at Vi.<anonymous> (json-rpc-provider.js:533:24)
    at Generator.throw (<anonymous>)
    at a (json-rpc-provider.js:6:64)
initiateSetupSubmission @ setup.js:172
await in initiateSetupSubmission (async)
(anonymous) @ common.js:205

If you're making this call from a browser with MetaMask, you won't even get the MetaMask transaction confirmation popup. 
17. Manually add a gas limit to the transaction call.  You can pick something very high, like 15 million (the block limit is 20M; 10M goes faster). 
18. Now, you'll get a confirmation popup and can send the transaction ([example: 0xf9bbdba3e4a5561e1454e14772e4f1efbbacd4f83e7d6f3fa1ddb69c89419cc4](https://mumbai.polygonscan.com/tx/0xf9bbdba3e4a5561e1454e14772e4f1efbbacd4f83e7d6f3fa1ddb69c89419cc4)) but it'll fail.  I'm not able to discern why at present. 

**Expected behavior**
The table-creation call at the end succeeds.
TableLand's documented limit of one table creation per transaction means that DApps requiring multiple tables (per TableLand recommendation to better leverage the power of relational structures) will have to be created in onlyOwner post-deploy calls like this.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome v103

**Additional context**
New user here; maybe it's just a matter of improving documentation to show how this can be as easy as claimed?

**Comment by joewagner** [comment]
@wbt Thanks for opening this! When I try to reproduce your example I see this error: https://portal.thirdweb.com/contracts/IERC721AUpgradeable#transfertononerc721receiverimplementer.  I'm guessing this is the same root cause as your issue, which is that the contract doesn't implement the ERC721Receiver interface. 
Can you try adding the following to your contract:
```
import "@openzeppelin/contracts/token/ERC721/utils/ERC721Holder.sol";

// ... later on ensure that your contract inherits ERC721Holder

contract CanvasGame is ERC721URIStorage, Ownable, ERC721Holder {
```

As for why it's working in the constructor...
I believe this is a nuance described in the [eth yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) section 7.1.  During the execution of the constructor function it's possible for the openzeppelin ERC721a contract tableland extends to use the `ERC721A__IERC721Receiver` interface to check the contract. 
This kind of functionality is something we are planning to build into the Canvas Game soon, but as you discovered it's currently just creating the table in the constructor

**Comment by sanderpick** [comment]
@joewagner Should this be closed? I think we have documented needing to implement `ERC721A__IERC721Receiver`, correct?

**Comment by joewagner** [comment]
@sanderpick I think we can close.  The top of [this docs page](https://docs.tableland.xyz/creating-tables-from-contracts) says "The creating contract **must be able to receive** an ERC721 token.".  That seems good to me.
